
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html
    networks:
      - lnmp-net
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - lnmp-net

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - lnmp-net

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"] # 开启AOF持久化
    networks:
      - lnmp-net
    ports:
      - "6380:6379"

networks:
  lnmp-net:
    driver: bridge

